import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
// import ThimProvider from "@/Provider/ThimProvider";
import Footer from "@/components/Footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col container mx-auto bg-background text-foreground">
          <Navbar />
          {children}
          <Footer/>
      </body>
    </html>
  );
}
