import dns from "node:dns"
dns.setServers(["8.8.8.8", "8.8.4.4"])

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import AuthModal from "@/components/AuthModal/AuthModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <ThemeProvider>
          <div className="container mx-auto flex flex-col min-h-screen px-4 md:px-0">
            <Navbar />
            <main className="grow">
              {children}
              <AuthModal />
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}